// Package business is a client for the Proof Business API: transactions,
// documents, signers, webhooks (v1 and v2), notaries, templates, referrals
// and integrations. See https://dev.proof.com for the API reference.
//
// Create a client with an API key and call it (sandbox shown):
//
//	auth := common.NewAuthenticatedDoer(common.APIKey(os.Getenv("PROOF_API_KEY")))
//	client, err := business.NewClientWithResponses(common.SandboxURL, business.WithHTTPClient(auth))
//	if err != nil { ... }
//	resp, err := client.GetAllTransactionsWithResponse(ctx, nil)
//	if err == nil { err = common.CheckResponseBody(resp.HTTPResponse, resp.Body) }
//
// Use the *WithResponse methods of ClientWithResponses. They return a typed
// result whose JSON200 (etc.) field is nil when the API answered with a
// different status, and a nil error for any HTTP status, so always check the
// status with common.CheckResponseBody(resp.HTTPResponse, resp.Body) before
// dereferencing JSON200.
//
// Endpoints that return document or ID-photo links take a DocumentUrlVersion
// parameter: "v2" gives Proof secure URLs, "v1" AWS S3 pre-signed URLs.
//
// Field-level documentation is on the generated struct fields (for example
// TransactionCreateParams and Signer). Optional fields are pointers; take the
// address of a local or use a helper like func ptr[T any](v T) *T { return &v }.
//
// Code in client.gen.go is generated by oapi-codegen from Proof's OpenAPI
// spec; do not edit it.
package business
