// Package realestate is a client for the Proof Real Estate (mortgage) API:
// mortgage transactions, documents, eNotes, notaries, title agencies and
// underwriters, recording locations, partner organizations and webhooks.
// See https://dev.proof.com for the API reference.
//
// Create a client with an API key and call it (sandbox shown):
//
//	auth := common.NewAuthenticatedDoer(common.APIKey(os.Getenv("PROOF_API_KEY")))
//	client, err := realestate.NewClientWithResponses(common.SandboxURL, realestate.WithHTTPClient(auth))
//	if err != nil { ... }
//	resp, err := client.GetAllMortgageTransactionsWithResponse(ctx, nil)
//	if err == nil { err = common.CheckResponseBody(resp.HTTPResponse, resp.Body) }
//
// Use the *WithResponse methods of ClientWithResponses. They return a nil
// error for any HTTP status and leave JSON200 nil on a non-200 status, so
// always check common.CheckResponseBody(resp.HTTPResponse, resp.Body) before
// dereferencing JSON200.
//
// Endpoints that return document links take a DocumentUrlVersion parameter:
// "v2" gives Proof secure URLs, "v1" AWS S3 pre-signed URLs.
//
// Code in client.gen.go is generated by oapi-codegen from Proof's OpenAPI
// spec; do not edit it.
package realestate
