// Package credentials provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package credentials

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AuthorizeVerifiableCredentialPresentationParamsResponseType.
const (
	VpToken AuthorizeVerifiableCredentialPresentationParamsResponseType = "vp_token"
)

// Valid indicates whether the value is a known member of the AuthorizeVerifiableCredentialPresentationParamsResponseType enum.
func (e AuthorizeVerifiableCredentialPresentationParamsResponseType) Valid() bool {
	switch e {
	case VpToken:
		return true
	default:
		return false
	}
}

// Defines values for AuthorizeVerifiableCredentialPresentationParamsResponseMode.
const (
	DirectPost AuthorizeVerifiableCredentialPresentationParamsResponseMode = "direct_post"
	Fragment   AuthorizeVerifiableCredentialPresentationParamsResponseMode = "fragment"
)

// Valid indicates whether the value is a known member of the AuthorizeVerifiableCredentialPresentationParamsResponseMode enum.
func (e AuthorizeVerifiableCredentialPresentationParamsResponseMode) Valid() bool {
	switch e {
	case DirectPost:
		return true
	case Fragment:
		return true
	default:
		return false
	}
}

// Defines values for AuthorizeVerifiableCredentialPresentationParamsScope.
const (
	UrnProofParamsScopeVerifiableCredentialsBasic AuthorizeVerifiableCredentialPresentationParamsScope = "urn:proof:params:scope:verifiable-credentials:basic"
)

// Valid indicates whether the value is a known member of the AuthorizeVerifiableCredentialPresentationParamsScope enum.
func (e AuthorizeVerifiableCredentialPresentationParamsScope) Valid() bool {
	switch e {
	case UrnProofParamsScopeVerifiableCredentialsBasic:
		return true
	default:
		return false
	}
}

// ErrorsObject defines model for errors_object.
type ErrorsObject struct {
	Errors *struct {
		Request *[]string `json:"request,omitempty"`
	} `json:"errors,omitempty"`
}

// AuthorizeVerifiableCredentialPresentationParams defines parameters for AuthorizeVerifiableCredentialPresentation.
type AuthorizeVerifiableCredentialPresentationParams struct {
	// ClientId Your Proof OAuth Application Client ID.
	ClientId string `form:"client_id" json:"client_id"`

	// ResponseType The method used to return the Verifiable Credential Presentation. Only `vp_token` is supported.
	ResponseType AuthorizeVerifiableCredentialPresentationParamsResponseType `form:"response_type" json:"response_type"`

	// ResponseMode How the Verifiable Credential Presentation will be returned to the Verifier. Use `fragment` to have the `vp_token` returned as a URL fragment on a redirect to `redirect_uri`, or `direct_post` to have Proof POST the `vp_token` to `response_uri`.
	ResponseMode AuthorizeVerifiableCredentialPresentationParamsResponseMode `form:"response_mode" json:"response_mode"`

	// RedirectUri Required when `response_mode` is `fragment`; not permitted otherwise. The redirect URI at which the Verifiable Credential Presentation will be returned as a URL fragment. Must match a redirect URI registered on your OAuth Application.
	RedirectUri *string `form:"redirect_uri,omitempty" json:"redirect_uri,omitempty"`

	// ResponseUri Required when `response_mode` is `direct_post`; not permitted otherwise. The URI to which Proof will POST the Verifiable Credential Presentation. Must match a redirect URI registered on your OAuth Application.
	ResponseUri *string `form:"response_uri,omitempty" json:"response_uri,omitempty"`

	// Scope Space-separated list of scopes that translate to DCQL queries.
	Scope AuthorizeVerifiableCredentialPresentationParamsScope `form:"scope" json:"scope"`

	// LoginHint The email address associated with the End-User you're requesting Verifiable Credential presentation from.
	LoginHint string `form:"login_hint" json:"login_hint"`

	// Nonce Opaque client-generated value bound to the presentation response to prevent replay.
	Nonce string `form:"nonce" json:"nonce"`

	// State Opaque value echoed back on the redirect to maintain state between the request and the callback.
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// TransactionData Space-separated base64url-encoded JSON objects. Each object carries transaction details the Verifier is asking the End-User to authorize, with the shape:
	//
	// - `type` (string, required): one of `urn:proof:params:vc:transaction-data:session-data`, `urn:proof:params:vc:transaction-data:payment-itemized:v1`, `urn:proof:params:vc:transaction-data:wire-instructions:v1`, or `urn:proof:params:vc:transaction-data:payment-mandate:v1`.
	// - `credential_ids` (array of strings, required): must be a single-element array matching the credential ID targeted by `scope` (currently `proof_id_default`).
	// - `payload` (object, required): type-specific fields authorized by the End-User.
	//
	// Example (decoded): `{"type":"urn:proof:params:vc:transaction-data:session-data","credential_ids":["proof_id_default"],"payload":{"ip_address":"203.0.113.0","device_id":"device-1989"}}`.
	TransactionData *string `form:"transaction_data,omitempty" json:"transaction_data,omitempty"`
}

// AuthorizeVerifiableCredentialPresentationParamsResponseType defines parameters for AuthorizeVerifiableCredentialPresentation.
type AuthorizeVerifiableCredentialPresentationParamsResponseType string

// AuthorizeVerifiableCredentialPresentationParamsResponseMode defines parameters for AuthorizeVerifiableCredentialPresentation.
type AuthorizeVerifiableCredentialPresentationParamsResponseMode string

// AuthorizeVerifiableCredentialPresentationParamsScope defines parameters for AuthorizeVerifiableCredentialPresentation.
type AuthorizeVerifiableCredentialPresentationParamsScope string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AuthorizeVerifiableCredentialPresentation request
	AuthorizeVerifiableCredentialPresentation(ctx context.Context, params *AuthorizeVerifiableCredentialPresentationParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AuthorizeVerifiableCredentialPresentation(ctx context.Context, params *AuthorizeVerifiableCredentialPresentationParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthorizeVerifiableCredentialPresentationRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAuthorizeVerifiableCredentialPresentationRequest generates requests for AuthorizeVerifiableCredentialPresentation
func NewAuthorizeVerifiableCredentialPresentationRequest(server string, params *AuthorizeVerifiableCredentialPresentationParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/verifiable-credentials/v1/presentation/authorize")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "client_id", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "response_type", params.ResponseType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "response_mode", params.ResponseMode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.RedirectUri != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "redirect_uri", *params.RedirectUri, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ResponseUri != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "response_uri", *params.ResponseUri, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "scope", params.Scope, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "login_hint", params.LoginHint, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "nonce", params.Nonce, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "state", *params.State, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.TransactionData != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "transaction_data", *params.TransactionData, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AuthorizeVerifiableCredentialPresentationWithResponse request
	AuthorizeVerifiableCredentialPresentationWithResponse(ctx context.Context, params *AuthorizeVerifiableCredentialPresentationParams, reqEditors ...RequestEditorFn) (*AuthorizeVerifiableCredentialPresentationResponse, error)
}

type AuthorizeVerifiableCredentialPresentationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorsObject
}

// Status returns HTTPResponse.Status
func (r AuthorizeVerifiableCredentialPresentationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AuthorizeVerifiableCredentialPresentationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AuthorizeVerifiableCredentialPresentationWithResponse request returning *AuthorizeVerifiableCredentialPresentationResponse
func (c *ClientWithResponses) AuthorizeVerifiableCredentialPresentationWithResponse(ctx context.Context, params *AuthorizeVerifiableCredentialPresentationParams, reqEditors ...RequestEditorFn) (*AuthorizeVerifiableCredentialPresentationResponse, error) {
	rsp, err := c.AuthorizeVerifiableCredentialPresentation(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthorizeVerifiableCredentialPresentationResponse(rsp)
}

// ParseAuthorizeVerifiableCredentialPresentationResponse parses an HTTP response from a AuthorizeVerifiableCredentialPresentationWithResponse call
func ParseAuthorizeVerifiableCredentialPresentationResponse(rsp *http.Response) (*AuthorizeVerifiableCredentialPresentationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AuthorizeVerifiableCredentialPresentationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorsObject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}
