// Package credentials is a client for the Proof Verifiable Credentials API,
// which requests an OID4VP Verifiable Credential Presentation from an
// End-User. See https://dev.proof.com for the API reference. Its two
// endpoints are used differently.
//
// # Authorize (browser redirect)
//
// The authorize endpoint answers 302 to a Proof-hosted page, so do not call it
// with the client. Build the URL and send the End-User's browser there:
//
//	req, err := credentials.NewAuthorizeVerifiableCredentialPresentationRequest(common.ProductionURL, &params)
//	if err != nil { ... }
//	http.Redirect(w, r, req.URL.String(), http.StatusFound)
//
// # x401 handoff (JSON POST)
//
// The x401 handoff endpoint is an ordinary POST: call
// CreatePresentationX401HandoffWithResponse and give JSON201.RequestUri to the
// End-User (typically via their AI agent). The spec declares no API-key
// security for it; the caller is identified by the signed request object in
// the body.
//
//	client, err := credentials.NewClientWithResponses(common.ProductionURL)
//	if err != nil { ... }
//	resp, err := client.CreatePresentationX401HandoffWithResponse(ctx, payload)
//	if err == nil { err = common.CheckResponseBody(resp.HTTPResponse, resp.Body) }
//
// As with every package in this module, a nil error from a *WithResponse
// method says nothing about the HTTP status; check it with
// common.CheckResponseBody(resp.HTTPResponse, resp.Body) before dereferencing
// JSON201.
//
// Code in client.gen.go is generated by oapi-codegen from Proof's OpenAPI
// spec; do not edit it.
package credentials
