// Package certificates provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package certificates

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	OAuthScopes      = "OAuth.Scopes"
)

// Defines values for PostV1CertificatesJSONBodyCertificateProfile.
const (
	PostV1CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl1 PostV1CertificatesJSONBodyCertificateProfile = "organization_authenticity_al1"
	PostV1CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl2 PostV1CertificatesJSONBodyCertificateProfile = "organization_authenticity_al2"
	PostV1CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl3 PostV1CertificatesJSONBodyCertificateProfile = "organization_authenticity_al3"
	PostV1CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl4 PostV1CertificatesJSONBodyCertificateProfile = "organization_authenticity_al4"
)

// Valid indicates whether the value is a known member of the PostV1CertificatesJSONBodyCertificateProfile enum.
func (e PostV1CertificatesJSONBodyCertificateProfile) Valid() bool {
	switch e {
	case PostV1CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl1:
		return true
	case PostV1CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl2:
		return true
	case PostV1CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl3:
		return true
	case PostV1CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl4:
		return true
	default:
		return false
	}
}

// Defines values for PostV1CertificatesIdSignJSONBodyAlgorithmOid.
const (
	N1284010045432 PostV1CertificatesIdSignJSONBodyAlgorithmOid = "1.2.840.10045.4.3.2"
)

// Valid indicates whether the value is a known member of the PostV1CertificatesIdSignJSONBodyAlgorithmOid enum.
func (e PostV1CertificatesIdSignJSONBodyAlgorithmOid) Valid() bool {
	switch e {
	case N1284010045432:
		return true
	default:
		return false
	}
}

// Defines values for PostV2CertificatesJSONBodyCertificateProfile.
const (
	PostV2CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl1 PostV2CertificatesJSONBodyCertificateProfile = "organization_authenticity_al1"
	PostV2CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl2 PostV2CertificatesJSONBodyCertificateProfile = "organization_authenticity_al2"
	PostV2CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl3 PostV2CertificatesJSONBodyCertificateProfile = "organization_authenticity_al3"
	PostV2CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl4 PostV2CertificatesJSONBodyCertificateProfile = "organization_authenticity_al4"
)

// Valid indicates whether the value is a known member of the PostV2CertificatesJSONBodyCertificateProfile enum.
func (e PostV2CertificatesJSONBodyCertificateProfile) Valid() bool {
	switch e {
	case PostV2CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl1:
		return true
	case PostV2CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl2:
		return true
	case PostV2CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl3:
		return true
	case PostV2CertificatesJSONBodyCertificateProfileOrganizationAuthenticityAl4:
		return true
	default:
		return false
	}
}

// OrganizationCertificateFullResponse Fully detailed response object for an Organization Certificate
type OrganizationCertificateFullResponse struct {
	// CertificateChain PEM-encoded certificate chain, end entity certificate first.
	CertificateChain *string `json:"certificate_chain,omitempty"`

	// CreatedAt ISO-8601 timestamp indicating certificate creation time.
	CreatedAt *string `json:"created_at,omitempty"`

	// External A certificate is external if its private key is stored by the customer.
	External *bool `json:"external,omitempty"`

	// Id UUID
	Id *string `json:"id,omitempty"`

	// Issuer OpenSSL-encoded subject of issuing certificate.
	Issuer *string `json:"issuer,omitempty"`

	// RevocationReason The reason the certificate was revoked. See RFC 5280 for possible values.
	RevocationReason *string `json:"revocation_reason,omitempty"`

	// RevokedAt ISO-8601 timestamp indicating certificate revocation time. Null unless certificate has been revoked.
	RevokedAt *string `json:"revoked_at,omitempty"`

	// SerialNumber Uppercase HEX-encoded X509 serial number
	SerialNumber *string `json:"serial_number,omitempty"`

	// Subject OpenSSL-formatted subject
	Subject *string `json:"subject,omitempty"`

	// ValidFrom ISO-8601 timestamp
	ValidFrom *string `json:"valid_from,omitempty"`

	// ValidTo ISO-8601 timestamp
	ValidTo *string `json:"valid_to,omitempty"`
}

// OrganizationCertificateShortResponse Short response object for an Organization Certificate (does not contain the certificate_chain).
type OrganizationCertificateShortResponse struct {
	// CreatedAt ISO-8601 timestamp indicating certificate creation time.
	CreatedAt *string `json:"created_at,omitempty"`

	// External A certificate is external if its private key is stored by the customer.
	External *bool `json:"external,omitempty"`

	// Id UUID
	Id *string `json:"id,omitempty"`

	// Issuer OpenSSL-encoded subject of issuing certificate.
	Issuer *string `json:"issuer,omitempty"`

	// RevocationReason The reason the certificate was revoked. See RFC 5280 for possible values.
	RevocationReason *string `json:"revocation_reason,omitempty"`

	// RevokedAt ISO-8601 timestamp indicating certificate revocation time. Null unless certificate has been revoked.
	RevokedAt *string `json:"revoked_at,omitempty"`

	// SerialNumber Uppercase HEX-encoded X509 serial number
	SerialNumber *string `json:"serial_number,omitempty"`

	// Subject OpenSSL-formatted subject
	Subject *string `json:"subject,omitempty"`

	// ValidFrom ISO-8601 timestamp
	ValidFrom *string `json:"valid_from,omitempty"`

	// ValidTo ISO-8601 timestamp
	ValidTo *string `json:"valid_to,omitempty"`
}

// GetV1CertificatesParams defines parameters for GetV1Certificates.
type GetV1CertificatesParams struct {
	// Limit Pagination parameter to set page size.
	Limit *string `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination parameter to set 0-based offset
	Offset *string `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostV1CertificatesJSONBody defines parameters for PostV1Certificates.
type PostV1CertificatesJSONBody struct {
	// CertificateProfile Requested Certificate Profile, corresponding to the Assurance Level at which your organization is compliant.
	CertificateProfile *PostV1CertificatesJSONBodyCertificateProfile `json:"certificate_profile,omitempty"`

	// CommonNamerequired CN field of subject. Use company name or something specific to the use-case.
	CommonNamerequired *string `json:"common_name *required,omitempty"`
}

// PostV1CertificatesJSONBodyCertificateProfile defines parameters for PostV1Certificates.
type PostV1CertificatesJSONBodyCertificateProfile string

// DeleteV1CertificatesIdParams defines parameters for DeleteV1CertificatesId.
type DeleteV1CertificatesIdParams struct {
	Reason *string `form:"reason,omitempty" json:"reason,omitempty"`
}

// PostV1CertificatesIdSignJSONBody defines parameters for PostV1CertificatesIdSign.
type PostV1CertificatesIdSignJSONBody struct {
	// AlgorithmOid The signing algorithm to use, specified by OID. Only ECDSA with SHA256 is currently supported.
	AlgorithmOid *PostV1CertificatesIdSignJSONBodyAlgorithmOid `json:"algorithm_oid,omitempty"`

	// Digests Base64-encoded SHA256 digests. A maximum of 25 digests can be signed in one request.
	Digests *[]string `json:"digests,omitempty"`
}

// PostV1CertificatesIdSignJSONBodyAlgorithmOid defines parameters for PostV1CertificatesIdSign.
type PostV1CertificatesIdSignJSONBodyAlgorithmOid string

// PostV2CertificatesJSONBody defines parameters for PostV2Certificates.
type PostV2CertificatesJSONBody struct {
	// CertificateProfile Requested Certificate Profile, corresponding to the Assurance Level at which your organization is compliant.
	CertificateProfile *PostV2CertificatesJSONBodyCertificateProfile `json:"certificate_profile,omitempty"`

	// Csrrequired PEM-encoded Certificate Signing Request. The Subject must be set in the CSR. The Country and Organization fields will be validated against your organization's records.
	Csrrequired *string `json:"csr *required,omitempty"`
}

// PostV2CertificatesJSONBodyCertificateProfile defines parameters for PostV2Certificates.
type PostV2CertificatesJSONBodyCertificateProfile string

// PostV1CertificatesJSONRequestBody defines body for PostV1Certificates for application/json ContentType.
type PostV1CertificatesJSONRequestBody PostV1CertificatesJSONBody

// PostV1CertificatesIdSignJSONRequestBody defines body for PostV1CertificatesIdSign for application/json ContentType.
type PostV1CertificatesIdSignJSONRequestBody PostV1CertificatesIdSignJSONBody

// PostV2CertificatesJSONRequestBody defines body for PostV2Certificates for application/json ContentType.
type PostV2CertificatesJSONRequestBody PostV2CertificatesJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetV1Certificates request
	GetV1Certificates(ctx context.Context, params *GetV1CertificatesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1CertificatesWithBody request with any body
	PostV1CertificatesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1Certificates(ctx context.Context, body PostV1CertificatesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteV1CertificatesId request
	DeleteV1CertificatesId(ctx context.Context, id string, params *DeleteV1CertificatesIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1CertificatesId request
	GetV1CertificatesId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1CertificatesIdSignWithBody request with any body
	PostV1CertificatesIdSignWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1CertificatesIdSign(ctx context.Context, id string, body PostV1CertificatesIdSignJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV2CertificatesWithBody request with any body
	PostV2CertificatesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV2Certificates(ctx context.Context, body PostV2CertificatesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetV1Certificates(ctx context.Context, params *GetV1CertificatesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1CertificatesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1CertificatesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1CertificatesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1Certificates(ctx context.Context, body PostV1CertificatesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1CertificatesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteV1CertificatesId(ctx context.Context, id string, params *DeleteV1CertificatesIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteV1CertificatesIdRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1CertificatesId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1CertificatesIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1CertificatesIdSignWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1CertificatesIdSignRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1CertificatesIdSign(ctx context.Context, id string, body PostV1CertificatesIdSignJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1CertificatesIdSignRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV2CertificatesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV2CertificatesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV2Certificates(ctx context.Context, body PostV2CertificatesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV2CertificatesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV1CertificatesRequest generates requests for GetV1Certificates
func NewGetV1CertificatesRequest(server string, params *GetV1CertificatesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/certificates")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "int"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "int"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1CertificatesRequest calls the generic PostV1Certificates builder with application/json body
func NewPostV1CertificatesRequest(server string, body PostV1CertificatesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1CertificatesRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1CertificatesRequestWithBody generates requests for PostV1Certificates with any type of body
func NewPostV1CertificatesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/certificates")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteV1CertificatesIdRequest generates requests for DeleteV1CertificatesId
func NewDeleteV1CertificatesIdRequest(server string, id string, params *DeleteV1CertificatesIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/certificates/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Reason != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "reason", *params.Reason, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1CertificatesIdRequest generates requests for GetV1CertificatesId
func NewGetV1CertificatesIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/certificates/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1CertificatesIdSignRequest calls the generic PostV1CertificatesIdSign builder with application/json body
func NewPostV1CertificatesIdSignRequest(server string, id string, body PostV1CertificatesIdSignJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1CertificatesIdSignRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPostV1CertificatesIdSignRequestWithBody generates requests for PostV1CertificatesIdSign with any type of body
func NewPostV1CertificatesIdSignRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/certificates/%s/sign", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostV2CertificatesRequest calls the generic PostV2Certificates builder with application/json body
func NewPostV2CertificatesRequest(server string, body PostV2CertificatesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV2CertificatesRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV2CertificatesRequestWithBody generates requests for PostV2Certificates with any type of body
func NewPostV2CertificatesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/certificates")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetV1CertificatesWithResponse request
	GetV1CertificatesWithResponse(ctx context.Context, params *GetV1CertificatesParams, reqEditors ...RequestEditorFn) (*GetV1CertificatesResponse, error)

	// PostV1CertificatesWithBodyWithResponse request with any body
	PostV1CertificatesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1CertificatesResponse, error)

	PostV1CertificatesWithResponse(ctx context.Context, body PostV1CertificatesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1CertificatesResponse, error)

	// DeleteV1CertificatesIdWithResponse request
	DeleteV1CertificatesIdWithResponse(ctx context.Context, id string, params *DeleteV1CertificatesIdParams, reqEditors ...RequestEditorFn) (*DeleteV1CertificatesIdResponse, error)

	// GetV1CertificatesIdWithResponse request
	GetV1CertificatesIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetV1CertificatesIdResponse, error)

	// PostV1CertificatesIdSignWithBodyWithResponse request with any body
	PostV1CertificatesIdSignWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1CertificatesIdSignResponse, error)

	PostV1CertificatesIdSignWithResponse(ctx context.Context, id string, body PostV1CertificatesIdSignJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1CertificatesIdSignResponse, error)

	// PostV2CertificatesWithBodyWithResponse request with any body
	PostV2CertificatesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV2CertificatesResponse, error)

	PostV2CertificatesWithResponse(ctx context.Context, body PostV2CertificatesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV2CertificatesResponse, error)
}

type GetV1CertificatesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Results *[]OrganizationCertificateShortResponse `json:"results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetV1CertificatesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1CertificatesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1CertificatesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Result Fully detailed response object for an Organization Certificate
		Result *OrganizationCertificateFullResponse `json:"result,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostV1CertificatesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1CertificatesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteV1CertificatesIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Result Fully detailed response object for an Organization Certificate
		Result *OrganizationCertificateFullResponse `json:"result,omitempty"`
	}
	JSON422 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r DeleteV1CertificatesIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteV1CertificatesIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1CertificatesIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Result Fully detailed response object for an Organization Certificate
		Result *OrganizationCertificateFullResponse `json:"result,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetV1CertificatesIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1CertificatesIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1CertificatesIdSignResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Result *[]string `json:"result,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostV1CertificatesIdSignResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1CertificatesIdSignResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV2CertificatesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Result Fully detailed response object for an Organization Certificate
		Result *OrganizationCertificateFullResponse `json:"result,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostV2CertificatesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV2CertificatesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetV1CertificatesWithResponse request returning *GetV1CertificatesResponse
func (c *ClientWithResponses) GetV1CertificatesWithResponse(ctx context.Context, params *GetV1CertificatesParams, reqEditors ...RequestEditorFn) (*GetV1CertificatesResponse, error) {
	rsp, err := c.GetV1Certificates(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1CertificatesResponse(rsp)
}

// PostV1CertificatesWithBodyWithResponse request with arbitrary body returning *PostV1CertificatesResponse
func (c *ClientWithResponses) PostV1CertificatesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1CertificatesResponse, error) {
	rsp, err := c.PostV1CertificatesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1CertificatesResponse(rsp)
}

func (c *ClientWithResponses) PostV1CertificatesWithResponse(ctx context.Context, body PostV1CertificatesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1CertificatesResponse, error) {
	rsp, err := c.PostV1Certificates(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1CertificatesResponse(rsp)
}

// DeleteV1CertificatesIdWithResponse request returning *DeleteV1CertificatesIdResponse
func (c *ClientWithResponses) DeleteV1CertificatesIdWithResponse(ctx context.Context, id string, params *DeleteV1CertificatesIdParams, reqEditors ...RequestEditorFn) (*DeleteV1CertificatesIdResponse, error) {
	rsp, err := c.DeleteV1CertificatesId(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteV1CertificatesIdResponse(rsp)
}

// GetV1CertificatesIdWithResponse request returning *GetV1CertificatesIdResponse
func (c *ClientWithResponses) GetV1CertificatesIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetV1CertificatesIdResponse, error) {
	rsp, err := c.GetV1CertificatesId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1CertificatesIdResponse(rsp)
}

// PostV1CertificatesIdSignWithBodyWithResponse request with arbitrary body returning *PostV1CertificatesIdSignResponse
func (c *ClientWithResponses) PostV1CertificatesIdSignWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1CertificatesIdSignResponse, error) {
	rsp, err := c.PostV1CertificatesIdSignWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1CertificatesIdSignResponse(rsp)
}

func (c *ClientWithResponses) PostV1CertificatesIdSignWithResponse(ctx context.Context, id string, body PostV1CertificatesIdSignJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1CertificatesIdSignResponse, error) {
	rsp, err := c.PostV1CertificatesIdSign(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1CertificatesIdSignResponse(rsp)
}

// PostV2CertificatesWithBodyWithResponse request with arbitrary body returning *PostV2CertificatesResponse
func (c *ClientWithResponses) PostV2CertificatesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV2CertificatesResponse, error) {
	rsp, err := c.PostV2CertificatesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV2CertificatesResponse(rsp)
}

func (c *ClientWithResponses) PostV2CertificatesWithResponse(ctx context.Context, body PostV2CertificatesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV2CertificatesResponse, error) {
	rsp, err := c.PostV2Certificates(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV2CertificatesResponse(rsp)
}

// ParseGetV1CertificatesResponse parses an HTTP response from a GetV1CertificatesWithResponse call
func ParseGetV1CertificatesResponse(rsp *http.Response) (*GetV1CertificatesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1CertificatesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Results *[]OrganizationCertificateShortResponse `json:"results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostV1CertificatesResponse parses an HTTP response from a PostV1CertificatesWithResponse call
func ParsePostV1CertificatesResponse(rsp *http.Response) (*PostV1CertificatesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1CertificatesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Result Fully detailed response object for an Organization Certificate
			Result *OrganizationCertificateFullResponse `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteV1CertificatesIdResponse parses an HTTP response from a DeleteV1CertificatesIdWithResponse call
func ParseDeleteV1CertificatesIdResponse(rsp *http.Response) (*DeleteV1CertificatesIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteV1CertificatesIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Result Fully detailed response object for an Organization Certificate
			Result *OrganizationCertificateFullResponse `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetV1CertificatesIdResponse parses an HTTP response from a GetV1CertificatesIdWithResponse call
func ParseGetV1CertificatesIdResponse(rsp *http.Response) (*GetV1CertificatesIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1CertificatesIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Result Fully detailed response object for an Organization Certificate
			Result *OrganizationCertificateFullResponse `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostV1CertificatesIdSignResponse parses an HTTP response from a PostV1CertificatesIdSignWithResponse call
func ParsePostV1CertificatesIdSignResponse(rsp *http.Response) (*PostV1CertificatesIdSignResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1CertificatesIdSignResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Result *[]string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostV2CertificatesResponse parses an HTTP response from a PostV2CertificatesWithResponse call
func ParsePostV2CertificatesResponse(rsp *http.Response) (*PostV2CertificatesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV2CertificatesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Result Fully detailed response object for an Organization Certificate
			Result *OrganizationCertificateFullResponse `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
