// Package certificates is a client for the Proof Organization Certificates
// API: create, list, fetch, delete and sign with an organization's
// certificates. See https://dev.proof.com for the API reference.
//
// Create a client with an API key and call it (sandbox shown):
//
//	auth := common.NewAuthenticatedDoer(common.APIKey(os.Getenv("PROOF_API_KEY")))
//	client, err := certificates.NewClientWithResponses(common.SandboxURL, certificates.WithHTTPClient(auth))
//	if err != nil { ... }
//	resp, err := client.GetV1CertificatesWithResponse(ctx, nil)
//	if err == nil { err = common.CheckResponseBody(resp.HTTPResponse, resp.Body) }
//
// Use the *WithResponse methods of ClientWithResponses. They return a nil
// error for any HTTP status and leave the JSON2xx fields nil on other
// statuses, so always check common.CheckResponseBody(resp.HTTPResponse,
// resp.Body) before dereferencing them.
//
// This API also accepts OAuth client-credentials tokens; see common.AuthProvider.
//
// Code in client.gen.go is generated by oapi-codegen from Proof's OpenAPI
// spec; do not edit it.
package certificates
