// Package logs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package logs

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	Api_keyScopes = "api_key.Scopes"
)

// ErrorsObject defines model for errors_object.
type ErrorsObject struct {
	Errors *[]string `json:"errors,omitempty"`
}

// SecurityEventObject defines model for security_event_object.
type SecurityEventObject struct {
	// ActivityId OCSF activity identifier
	ActivityId *int `json:"activity_id,omitempty"`

	// ActivityName OCSF activity name
	ActivityName *string `json:"activity_name,omitempty"`

	// CategoryName OCSF category name
	CategoryName *string `json:"category_name,omitempty"`

	// CategoryUid OCSF category identifier
	CategoryUid *int `json:"category_uid,omitempty"`

	// ClassName OCSF event class name
	ClassName *string `json:"class_name,omitempty"`

	// ClassUid OCSF event class identifier
	ClassUid *int `json:"class_uid,omitempty"`
	Metadata *struct {
		Product *struct {
			Name       *string `json:"name,omitempty"`
			VendorName *string `json:"vendor_name,omitempty"`
		} `json:"product,omitempty"`

		// Version OCSF schema version
		Version *string `json:"version,omitempty"`
	} `json:"metadata,omitempty"`

	// Severity OCSF severity label
	Severity *string `json:"severity,omitempty"`

	// SeverityId OCSF severity identifier
	SeverityId *int `json:"severity_id,omitempty"`

	// Time Event timestamp as Unix epoch
	Time *int `json:"time,omitempty"`

	// TypeUid OCSF event type identifier
	TypeUid *int `json:"type_uid,omitempty"`
}

// SecurityEventsResponse defines model for security_events_response.
type SecurityEventsResponse struct {
	Data *[]SecurityEventObject `json:"data,omitempty"`
	Meta *struct {
		// Count Number of events in this response
		Count *int `json:"count,omitempty"`

		// HasMore Whether more results are available
		HasMore *bool `json:"has_more,omitempty"`

		// NextCursor Cursor for fetching the next page of results
		NextCursor *string `json:"next_cursor,omitempty"`
	} `json:"meta,omitempty"`
}

// ListSecurityEventsParams defines parameters for ListSecurityEvents.
type ListSecurityEventsParams struct {
	// Limit Number of events to return per page (1-1000, default 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor for pagination. Use the next_cursor value from a previous response to fetch the next page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Since ISO 8601 timestamp. Only return events ingested at or after this time. Maximum 90 days in the past. Ignored when cursor is provided.
	Since *string `form:"since,omitempty" json:"since,omitempty"`

	// ClassUid Filter by OCSF event class identifier
	ClassUid *int `form:"class_uid,omitempty" json:"class_uid,omitempty"`

	// SeverityId Filter by OCSF severity identifier
	SeverityId *int `form:"severity_id,omitempty" json:"severity_id,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListSecurityEvents request
	ListSecurityEvents(ctx context.Context, params *ListSecurityEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListSecurityEvents(ctx context.Context, params *ListSecurityEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSecurityEventsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListSecurityEventsRequest generates requests for ListSecurityEvents
func NewListSecurityEventsRequest(server string, params *ListSecurityEventsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/logs/v1/security-events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Since != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "since", *params.Since, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ClassUid != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "class_uid", *params.ClassUid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SeverityId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "severity_id", *params.SeverityId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListSecurityEventsWithResponse request
	ListSecurityEventsWithResponse(ctx context.Context, params *ListSecurityEventsParams, reqEditors ...RequestEditorFn) (*ListSecurityEventsResponse, error)
}

type ListSecurityEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SecurityEventsResponse
	JSON400      *ErrorsObject
	JSON403      *ErrorsObject
}

// Status returns HTTPResponse.Status
func (r ListSecurityEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSecurityEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListSecurityEventsWithResponse request returning *ListSecurityEventsResponse
func (c *ClientWithResponses) ListSecurityEventsWithResponse(ctx context.Context, params *ListSecurityEventsParams, reqEditors ...RequestEditorFn) (*ListSecurityEventsResponse, error) {
	rsp, err := c.ListSecurityEvents(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSecurityEventsResponse(rsp)
}

// ParseListSecurityEventsResponse parses an HTTP response from a ListSecurityEventsWithResponse call
func ParseListSecurityEventsResponse(rsp *http.Response) (*ListSecurityEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSecurityEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SecurityEventsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorsObject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorsObject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}
