// Package logs is a client for the Proof Logs API, which lists an
// organization's security events (OCSF-formatted, cursor-paginated). See
// https://dev.proof.com for the API reference.
//
// Create a client with an API key and call it (sandbox shown):
//
//	auth := common.NewAuthenticatedDoer(common.APIKey(os.Getenv("PROOF_API_KEY")))
//	client, err := logs.NewClientWithResponses(common.SandboxURL, logs.WithHTTPClient(auth))
//	if err != nil { ... }
//	resp, err := client.ListSecurityEventsWithResponse(ctx, nil)
//	if err == nil { err = common.CheckResponseBody(resp.HTTPResponse, resp.Body) }
//
// Use the *WithResponse methods of ClientWithResponses. They return a nil
// error for any HTTP status and leave JSON200 nil on a non-200 status, so
// always check common.CheckResponseBody(resp.HTTPResponse, resp.Body) before
// dereferencing JSON200. To page, pass JSON200.Meta.NextCursor back as
// ListSecurityEventsParams.Cursor while Meta.HasMore is true.
//
// Code in client.gen.go is generated by oapi-codegen from Proof's OpenAPI
// spec; do not edit it.
package logs
