// Package scim provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package scim

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	Sec0Scopes = "sec0.Scopes"
)

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// StartIndex The 1-based index of the first result in the current set of list results
	StartIndex *int32 `form:"startIndex,omitempty" json:"startIndex,omitempty"`

	// Count Non-negative integer. Specifies the desired maximum number of query results per page
	Count *int32 `form:"count,omitempty" json:"count,omitempty"`

	// Filter Filter by userName. e.g. userName eq "example@example.com"
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody struct {
	// Active Used to indicate whether the identity is active (true) or deprovisioned (false).
	Active *string `json:"active,omitempty"`

	// Emails List of user emails, only primary supported and only a predefined allow list of domains are accepted.
	Emails *[]string `json:"emails,omitempty"`

	// ExternalId This identifier is generated by the SAML provider, and is used as a unique ID by the SAML provider to match against a Notarize user.
	ExternalId *string `json:"externalId,omitempty"`

	// Name The full name of the user, represented by a `name` object
	Name *struct {
		// FamilyName The last name of the user
		FamilyName *string `json:"familyName,omitempty"`

		// GivenName The first name of the user
		GivenName *string `json:"givenName,omitempty"`
	} `json:"name,omitempty"`

	// Roles List of user roles, only primary supported. One of “owner”, “admin” or “employee”.
	Roles *[]string `json:"roles,omitempty"`

	// UserName Email address as username.
	UserName string `json:"userName"`
}

// CreateUserParams defines parameters for CreateUser.
type CreateUserParams struct {
	Accept *string `json:"accept,omitempty"`
}

// DeleteUserParams defines parameters for DeleteUser.
type DeleteUserParams struct {
	Accept *string `json:"accept,omitempty"`
}

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	Accept *string `json:"accept,omitempty"`
}

// PatchUserJSONBody defines parameters for PatchUser.
type PatchUserJSONBody struct {
	// Operations Set of operations to be performed
	Operations struct {
		// Op Can be one of: add, remove, replace
		Op string `json:"op"`

		// Path Path to value in resource. Top level values ("name") and child values ("name.givenName") supported.
		Path *string `json:"path,omitempty"`

		// Value Can be an object, array, or string. Value may be dependent on "path"
		Value *string `json:"value,omitempty"`
	} `json:"Operations"`
}

// PatchUserParams defines parameters for PatchUser.
type PatchUserParams struct {
	Accept *string `json:"accept,omitempty"`
}

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody struct {
	// Active Used to indicate whether the identity is active (true) or deprovisioned (false).
	Active *string `json:"active,omitempty"`

	// Emails List of user emails, only primary supported and only a predefined allow list of domains are accepted.
	Emails *[]string `json:"emails,omitempty"`

	// ExternalId This identifier is generated by the SAML provider, and is used as a unique ID by the SAML provider to match against a Notarize user.
	ExternalId *string `json:"externalId,omitempty"`

	// Name The full name of the user, represented by a `name` object
	Name *struct {
		// FamilyName The last name of the user
		FamilyName *string `json:"familyName,omitempty"`

		// GivenName The first name of the user
		GivenName *string `json:"givenName,omitempty"`
	} `json:"name,omitempty"`

	// Roles List of user roles, only primary supported. One of “owner”, “admin” or “employee”.
	Roles *[]string `json:"roles,omitempty"`

	// UserName Email address as username.
	UserName string `json:"userName"`
}

// UpdateUserParams defines parameters for UpdateUser.
type UpdateUserParams struct {
	Accept *string `json:"accept,omitempty"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// PatchUserJSONRequestBody defines body for PatchUser for application/json ContentType.
type PatchUserJSONRequestBody PatchUserJSONBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetResourceTypes request
	GetResourceTypes(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RetrieveUsersSchema request
	RetrieveUsersSchema(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetServiceProviderConfig request
	GetServiceProviderConfig(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListUsers request
	ListUsers(ctx context.Context, organizationId string, params *ListUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUserWithBody request with any body
	CreateUserWithBody(ctx context.Context, organizationId string, params *CreateUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateUser(ctx context.Context, organizationId string, params *CreateUserParams, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteUser request
	DeleteUser(ctx context.Context, organizationId string, userId string, params *DeleteUserParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUser request
	GetUser(ctx context.Context, organizationId string, userId string, params *GetUserParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchUserWithBody request with any body
	PatchUserWithBody(ctx context.Context, organizationId string, userId string, params *PatchUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchUser(ctx context.Context, organizationId string, userId string, params *PatchUserParams, body PatchUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateUserWithBody request with any body
	UpdateUserWithBody(ctx context.Context, organizationId string, userId string, params *UpdateUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateUser(ctx context.Context, organizationId string, userId string, params *UpdateUserParams, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetResourceTypes(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetResourceTypesRequest(c.Server, organizationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RetrieveUsersSchema(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRetrieveUsersSchemaRequest(c.Server, organizationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetServiceProviderConfig(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetServiceProviderConfigRequest(c.Server, organizationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListUsers(ctx context.Context, organizationId string, params *ListUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListUsersRequest(c.Server, organizationId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUserWithBody(ctx context.Context, organizationId string, params *CreateUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUserRequestWithBody(c.Server, organizationId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUser(ctx context.Context, organizationId string, params *CreateUserParams, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUserRequest(c.Server, organizationId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteUser(ctx context.Context, organizationId string, userId string, params *DeleteUserParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteUserRequest(c.Server, organizationId, userId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUser(ctx context.Context, organizationId string, userId string, params *GetUserParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserRequest(c.Server, organizationId, userId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchUserWithBody(ctx context.Context, organizationId string, userId string, params *PatchUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchUserRequestWithBody(c.Server, organizationId, userId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchUser(ctx context.Context, organizationId string, userId string, params *PatchUserParams, body PatchUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchUserRequest(c.Server, organizationId, userId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateUserWithBody(ctx context.Context, organizationId string, userId string, params *UpdateUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateUserRequestWithBody(c.Server, organizationId, userId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateUser(ctx context.Context, organizationId string, userId string, params *UpdateUserParams, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateUserRequest(c.Server, organizationId, userId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetResourceTypesRequest generates requests for GetResourceTypes
func NewGetResourceTypesRequest(server string, organizationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/ResourceTypes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRetrieveUsersSchemaRequest generates requests for RetrieveUsersSchema
func NewRetrieveUsersSchemaRequest(server string, organizationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Schemas/Users", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetServiceProviderConfigRequest generates requests for GetServiceProviderConfig
func NewGetServiceProviderConfigRequest(server string, organizationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/ServiceProviderConfig", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListUsersRequest generates requests for ListUsers
func NewListUsersRequest(server string, organizationId string, params *ListUsersParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Users", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.StartIndex != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "startIndex", *params.StartIndex, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Count != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "count", *params.Count, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Filter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter", *params.Filter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateUserRequest calls the generic CreateUser builder with application/json body
func NewCreateUserRequest(server string, organizationId string, params *CreateUserParams, body CreateUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateUserRequestWithBody(server, organizationId, params, "application/json", bodyReader)
}

// NewCreateUserRequestWithBody generates requests for CreateUser with any type of body
func NewCreateUserRequestWithBody(server string, organizationId string, params *CreateUserParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Users", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept", headerParam0)
		}

	}

	return req, nil
}

// NewDeleteUserRequest generates requests for DeleteUser
func NewDeleteUserRequest(server string, organizationId string, userId string, params *DeleteUserParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Users/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept", headerParam0)
		}

	}

	return req, nil
}

// NewGetUserRequest generates requests for GetUser
func NewGetUserRequest(server string, organizationId string, userId string, params *GetUserParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Users/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept", headerParam0)
		}

	}

	return req, nil
}

// NewPatchUserRequest calls the generic PatchUser builder with application/json body
func NewPatchUserRequest(server string, organizationId string, userId string, params *PatchUserParams, body PatchUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchUserRequestWithBody(server, organizationId, userId, params, "application/json", bodyReader)
}

// NewPatchUserRequestWithBody generates requests for PatchUser with any type of body
func NewPatchUserRequestWithBody(server string, organizationId string, userId string, params *PatchUserParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Users/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept", headerParam0)
		}

	}

	return req, nil
}

// NewUpdateUserRequest calls the generic UpdateUser builder with application/json body
func NewUpdateUserRequest(server string, organizationId string, userId string, params *UpdateUserParams, body UpdateUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateUserRequestWithBody(server, organizationId, userId, params, "application/json", bodyReader)
}

// NewUpdateUserRequestWithBody generates requests for UpdateUser with any type of body
func NewUpdateUserRequestWithBody(server string, organizationId string, userId string, params *UpdateUserParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Users/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetResourceTypesWithResponse request
	GetResourceTypesWithResponse(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*GetResourceTypesResponse, error)

	// RetrieveUsersSchemaWithResponse request
	RetrieveUsersSchemaWithResponse(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*RetrieveUsersSchemaResponse, error)

	// GetServiceProviderConfigWithResponse request
	GetServiceProviderConfigWithResponse(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*GetServiceProviderConfigResponse, error)

	// ListUsersWithResponse request
	ListUsersWithResponse(ctx context.Context, organizationId string, params *ListUsersParams, reqEditors ...RequestEditorFn) (*ListUsersResponse, error)

	// CreateUserWithBodyWithResponse request with any body
	CreateUserWithBodyWithResponse(ctx context.Context, organizationId string, params *CreateUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUserResponse, error)

	CreateUserWithResponse(ctx context.Context, organizationId string, params *CreateUserParams, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUserResponse, error)

	// DeleteUserWithResponse request
	DeleteUserWithResponse(ctx context.Context, organizationId string, userId string, params *DeleteUserParams, reqEditors ...RequestEditorFn) (*DeleteUserResponse, error)

	// GetUserWithResponse request
	GetUserWithResponse(ctx context.Context, organizationId string, userId string, params *GetUserParams, reqEditors ...RequestEditorFn) (*GetUserResponse, error)

	// PatchUserWithBodyWithResponse request with any body
	PatchUserWithBodyWithResponse(ctx context.Context, organizationId string, userId string, params *PatchUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchUserResponse, error)

	PatchUserWithResponse(ctx context.Context, organizationId string, userId string, params *PatchUserParams, body PatchUserJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchUserResponse, error)

	// UpdateUserWithBodyWithResponse request with any body
	UpdateUserWithBodyWithResponse(ctx context.Context, organizationId string, userId string, params *UpdateUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error)

	UpdateUserWithResponse(ctx context.Context, organizationId string, userId string, params *UpdateUserParams, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error)
}

type GetResourceTypesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Resources *[]struct {
			Description *string `json:"description,omitempty"`
			Endpoint    *string `json:"endpoint,omitempty"`
			Id          *string `json:"id,omitempty"`
			Meta        *struct {
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name    *string   `json:"name,omitempty"`
			Schema  *string   `json:"schema,omitempty"`
			Schemas *[]string `json:"schemas,omitempty"`
		} `json:"Resources,omitempty"`
		ItemsPerPage *int      `json:"itemsPerPage,omitempty"`
		Schemas      *[]string `json:"schemas,omitempty"`
		StartIndex   *int      `json:"startIndex,omitempty"`
		TotalResults *int      `json:"totalResults,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetResourceTypesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetResourceTypesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RetrieveUsersSchemaResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Description *string `json:"description,omitempty"`
		Properties  *struct {
			Active *struct {
				Description *string `json:"description,omitempty"`
				Examples    *[]bool `json:"examples,omitempty"`
				Type        *string `json:"type,omitempty"`
			} `json:"active,omitempty"`
			DisplayName *struct {
				Description *string   `json:"description,omitempty"`
				Examples    *[]string `json:"examples,omitempty"`
				Type        *[]string `json:"type,omitempty"`
			} `json:"displayName,omitempty"`
			Emails *struct {
				Description *string `json:"description,omitempty"`
				Examples    *[]struct {
					Primary *bool   `json:"primary,omitempty"`
					Value   *string `json:"value,omitempty"`
				} `json:"examples,omitempty"`
				Items *struct {
					Properties *struct {
						Primary *struct {
							Type *string `json:"type,omitempty"`
						} `json:"primary,omitempty"`
						Type *struct {
							Type *string `json:"type,omitempty"`
						} `json:"type,omitempty"`
						Value *struct {
							Type *string `json:"type,omitempty"`
						} `json:"value,omitempty"`
					} `json:"properties,omitempty"`
					Required *[]string `json:"required,omitempty"`
					Type     *string   `json:"type,omitempty"`
				} `json:"items,omitempty"`
				Type *string `json:"type,omitempty"`
			} `json:"emails,omitempty"`
			ExternalId *struct {
				Description *string   `json:"description,omitempty"`
				Examples    *[]string `json:"examples,omitempty"`
				Type        *[]string `json:"type,omitempty"`
			} `json:"externalId,omitempty"`
			Id *struct {
				Description *string   `json:"description,omitempty"`
				Examples    *[]string `json:"examples,omitempty"`
				Type        *string   `json:"type,omitempty"`
			} `json:"id,omitempty"`
			Meta *struct {
				Properties *struct {
					Created *struct {
						Examples *[]string `json:"examples,omitempty"`
						Format   *string   `json:"format,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"created,omitempty"`
					LastModified *struct {
						Examples *[]string `json:"examples,omitempty"`
						Format   *string   `json:"format,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"lastModified,omitempty"`
					Location *struct {
						Examples *[]string `json:"examples,omitempty"`
						Format   *string   `json:"format,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"location,omitempty"`
					ResourceType *struct {
						Examples *[]string `json:"examples,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"resourceType,omitempty"`
				} `json:"properties,omitempty"`
				Type *string `json:"type,omitempty"`
			} `json:"meta,omitempty"`
			Name *struct {
				Example *struct {
					FamilyName *string `json:"familyName,omitempty"`
					GivenName  *string `json:"givenName,omitempty"`
				} `json:"example,omitempty"`
				Properties *struct {
					FamilyName *struct {
						Type *[]string `json:"type,omitempty"`
					} `json:"familyName,omitempty"`
					GivenName *struct {
						Type *[]string `json:"type,omitempty"`
					} `json:"givenName,omitempty"`
				} `json:"properties,omitempty"`
				Type *string `json:"type,omitempty"`
			} `json:"name,omitempty"`
			Operations *struct {
				Description *string `json:"description,omitempty"`
				Examples    *[]struct {
					Op    *string `json:"op,omitempty"`
					Value *struct {
						Active *bool `json:"active,omitempty"`
					} `json:"value,omitempty"`
				} `json:"examples,omitempty"`
				Items *struct {
					Properties *struct {
						Op *struct {
							Enum *[]string `json:"enum,omitempty"`
							Type *string   `json:"type,omitempty"`
						} `json:"op,omitempty"`
						Path *struct {
							Type *string `json:"type,omitempty"`
						} `json:"path,omitempty"`
						Value *struct {
							OneOf *[]struct {
								Type *string `json:"type,omitempty"`
							} `json:"oneOf,omitempty"`
						} `json:"value,omitempty"`
					} `json:"properties,omitempty"`
					Required *[]string `json:"required,omitempty"`
					Type     *string   `json:"type,omitempty"`
				} `json:"items,omitempty"`
				MinItems *int    `json:"minItems,omitempty"`
				Type     *string `json:"type,omitempty"`
			} `json:"operations,omitempty"`
			Roles *struct {
				Items *struct {
					Properties *struct {
						Display *struct {
							Type *string `json:"type,omitempty"`
						} `json:"display,omitempty"`
						Primary *struct {
							Type *string `json:"type,omitempty"`
						} `json:"primary,omitempty"`
						Value *struct {
							Type *string `json:"type,omitempty"`
						} `json:"value,omitempty"`
					} `json:"properties,omitempty"`
					Type *string `json:"type,omitempty"`
				} `json:"items,omitempty"`
				Type *string `json:"type,omitempty"`
			} `json:"roles,omitempty"`
			Schemas *struct {
				Description *string `json:"description,omitempty"`
				Items       *struct {
					Examples *[]string `json:"examples,omitempty"`
					Type     *string   `json:"type,omitempty"`
				} `json:"items,omitempty"`
				MinItems *int    `json:"minItems,omitempty"`
				Type     *string `json:"type,omitempty"`
			} `json:"schemas,omitempty"`
			UserName *struct {
				Description *string   `json:"description,omitempty"`
				Examples    *[]string `json:"examples,omitempty"`
				Type        *[]string `json:"type,omitempty"`
			} `json:"userName,omitempty"`
		} `json:"properties,omitempty"`
		Required *[]string `json:"required,omitempty"`
		Title    *string   `json:"title,omitempty"`
		Type     *string   `json:"type,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r RetrieveUsersSchemaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RetrieveUsersSchemaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetServiceProviderConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		AuthenticationSchemes *[]struct {
			Description      *string `json:"description,omitempty"`
			DocumentationUri *string `json:"documentationUri,omitempty"`
			Name             *string `json:"name,omitempty"`
			Primary          *bool   `json:"primary,omitempty"`
			Type             *string `json:"type,omitempty"`
		} `json:"authenticationSchemes,omitempty"`
		Bulk *struct {
			Supported *bool `json:"supported,omitempty"`
		} `json:"bulk,omitempty"`
		ChangePassword *struct {
			Supported *bool `json:"supported,omitempty"`
		} `json:"changePassword,omitempty"`
		DocumentationUri *string `json:"documentationUri,omitempty"`
		Etag             *struct {
			Supported *bool `json:"supported,omitempty"`
		} `json:"etag,omitempty"`
		Filter *struct {
			Supported *bool `json:"supported,omitempty"`
		} `json:"filter,omitempty"`
		Meta *struct {
			Location     *string `json:"location,omitempty"`
			ResourceType *string `json:"resourceType,omitempty"`
		} `json:"meta,omitempty"`
		Name  *string `json:"name,omitempty"`
		Patch *struct {
			Supported *bool `json:"supported,omitempty"`
		} `json:"patch,omitempty"`
		Schemas *[]string `json:"schemas,omitempty"`
		Sort    *struct {
			Supported *bool `json:"supported,omitempty"`
		} `json:"sort,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetServiceProviderConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetServiceProviderConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Resources *[]struct {
			Active *bool `json:"active,omitempty"`
			Emails *[]struct {
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"emails,omitempty"`
			ExternalId interface{} `json:"externalId,omitempty"`
			Id         *string     `json:"id,omitempty"`
			Meta       *struct {
				Created      *string `json:"created,omitempty"`
				LastModified *string `json:"lastModified,omitempty"`
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name *struct {
				FamilyName *string `json:"familyName,omitempty"`
				GivenName  *string `json:"givenName,omitempty"`
			} `json:"name,omitempty"`
			Roles *[]struct {
				Display *string `json:"display,omitempty"`
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"roles,omitempty"`
			Schemas  *[]string `json:"schemas,omitempty"`
			UserName *string   `json:"userName,omitempty"`
		} `json:"Resources,omitempty"`
		ItemsPerPage *int      `json:"itemsPerPage,omitempty"`
		Schemas      *[]string `json:"schemas,omitempty"`
		StartIndex   *int      `json:"startIndex,omitempty"`
		TotalResults *int      `json:"totalResults,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ListUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Active *bool `json:"active,omitempty"`
		Emails *[]struct {
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"emails,omitempty"`
		ExternalId *string `json:"externalId,omitempty"`
		Id         *string `json:"id,omitempty"`
		Meta       *struct {
			Created      *string `json:"created,omitempty"`
			LastModified *string `json:"lastModified,omitempty"`
			Location     *string `json:"location,omitempty"`
			ResourceType *string `json:"resourceType,omitempty"`
		} `json:"meta,omitempty"`
		Name *struct {
			FamilyName *string `json:"familyName,omitempty"`
			GivenName  *string `json:"givenName,omitempty"`
		} `json:"name,omitempty"`
		Roles *[]struct {
			Display *string `json:"display,omitempty"`
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"roles,omitempty"`
		Schemas  *[]string `json:"schemas,omitempty"`
		UserName *string   `json:"userName,omitempty"`
	}
	JSON400 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CreateUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON204      *map[string]interface{}
	JSON403      *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON422 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r DeleteUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Active *bool `json:"active,omitempty"`
		Emails *[]struct {
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"emails,omitempty"`
		ExternalId *string `json:"externalId,omitempty"`
		Id         *string `json:"id,omitempty"`
		Meta       *struct {
			Created      *string `json:"created,omitempty"`
			LastModified *string `json:"lastModified,omitempty"`
			Location     *string `json:"location,omitempty"`
			ResourceType *string `json:"resourceType,omitempty"`
		} `json:"meta,omitempty"`
		Name *struct {
			FamilyName *string `json:"familyName,omitempty"`
			GivenName  *string `json:"givenName,omitempty"`
		} `json:"name,omitempty"`
		Roles *[]struct {
			Display *string `json:"display,omitempty"`
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"roles,omitempty"`
		Schemas  *[]string `json:"schemas,omitempty"`
		UserName *string   `json:"userName,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Active *bool `json:"active,omitempty"`
		Emails *[]struct {
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"emails,omitempty"`
		ExternalId *string `json:"externalId,omitempty"`
		Id         *string `json:"id,omitempty"`
		Meta       *struct {
			Created      *string `json:"created,omitempty"`
			LastModified *string `json:"lastModified,omitempty"`
			Location     *string `json:"location,omitempty"`
			ResourceType *string `json:"resourceType,omitempty"`
		} `json:"meta,omitempty"`
		Name *struct {
			FamilyName *string `json:"familyName,omitempty"`
			GivenName  *string `json:"givenName,omitempty"`
		} `json:"name,omitempty"`
		Roles *[]struct {
			Display *string `json:"display,omitempty"`
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"roles,omitempty"`
		Schemas  *[]string `json:"schemas,omitempty"`
		UserName *string   `json:"userName,omitempty"`
	}
	JSON400 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PatchUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Active *bool `json:"active,omitempty"`
		Emails *[]struct {
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"emails,omitempty"`
		ExternalId *string `json:"externalId,omitempty"`
		Id         *string `json:"id,omitempty"`
		Meta       *struct {
			Created      *string `json:"created,omitempty"`
			LastModified *string `json:"lastModified,omitempty"`
			Location     *string `json:"location,omitempty"`
			ResourceType *string `json:"resourceType,omitempty"`
		} `json:"meta,omitempty"`
		Name *struct {
			FamilyName *string `json:"familyName,omitempty"`
			GivenName  *string `json:"givenName,omitempty"`
		} `json:"name,omitempty"`
		Roles *[]struct {
			Display *string `json:"display,omitempty"`
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"roles,omitempty"`
		Schemas  *[]string `json:"schemas,omitempty"`
		UserName *string   `json:"userName,omitempty"`
	}
	JSON400 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r UpdateUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetResourceTypesWithResponse request returning *GetResourceTypesResponse
func (c *ClientWithResponses) GetResourceTypesWithResponse(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*GetResourceTypesResponse, error) {
	rsp, err := c.GetResourceTypes(ctx, organizationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetResourceTypesResponse(rsp)
}

// RetrieveUsersSchemaWithResponse request returning *RetrieveUsersSchemaResponse
func (c *ClientWithResponses) RetrieveUsersSchemaWithResponse(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*RetrieveUsersSchemaResponse, error) {
	rsp, err := c.RetrieveUsersSchema(ctx, organizationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRetrieveUsersSchemaResponse(rsp)
}

// GetServiceProviderConfigWithResponse request returning *GetServiceProviderConfigResponse
func (c *ClientWithResponses) GetServiceProviderConfigWithResponse(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*GetServiceProviderConfigResponse, error) {
	rsp, err := c.GetServiceProviderConfig(ctx, organizationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetServiceProviderConfigResponse(rsp)
}

// ListUsersWithResponse request returning *ListUsersResponse
func (c *ClientWithResponses) ListUsersWithResponse(ctx context.Context, organizationId string, params *ListUsersParams, reqEditors ...RequestEditorFn) (*ListUsersResponse, error) {
	rsp, err := c.ListUsers(ctx, organizationId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListUsersResponse(rsp)
}

// CreateUserWithBodyWithResponse request with arbitrary body returning *CreateUserResponse
func (c *ClientWithResponses) CreateUserWithBodyWithResponse(ctx context.Context, organizationId string, params *CreateUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUserResponse, error) {
	rsp, err := c.CreateUserWithBody(ctx, organizationId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUserResponse(rsp)
}

func (c *ClientWithResponses) CreateUserWithResponse(ctx context.Context, organizationId string, params *CreateUserParams, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUserResponse, error) {
	rsp, err := c.CreateUser(ctx, organizationId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUserResponse(rsp)
}

// DeleteUserWithResponse request returning *DeleteUserResponse
func (c *ClientWithResponses) DeleteUserWithResponse(ctx context.Context, organizationId string, userId string, params *DeleteUserParams, reqEditors ...RequestEditorFn) (*DeleteUserResponse, error) {
	rsp, err := c.DeleteUser(ctx, organizationId, userId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteUserResponse(rsp)
}

// GetUserWithResponse request returning *GetUserResponse
func (c *ClientWithResponses) GetUserWithResponse(ctx context.Context, organizationId string, userId string, params *GetUserParams, reqEditors ...RequestEditorFn) (*GetUserResponse, error) {
	rsp, err := c.GetUser(ctx, organizationId, userId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserResponse(rsp)
}

// PatchUserWithBodyWithResponse request with arbitrary body returning *PatchUserResponse
func (c *ClientWithResponses) PatchUserWithBodyWithResponse(ctx context.Context, organizationId string, userId string, params *PatchUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchUserResponse, error) {
	rsp, err := c.PatchUserWithBody(ctx, organizationId, userId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchUserResponse(rsp)
}

func (c *ClientWithResponses) PatchUserWithResponse(ctx context.Context, organizationId string, userId string, params *PatchUserParams, body PatchUserJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchUserResponse, error) {
	rsp, err := c.PatchUser(ctx, organizationId, userId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchUserResponse(rsp)
}

// UpdateUserWithBodyWithResponse request with arbitrary body returning *UpdateUserResponse
func (c *ClientWithResponses) UpdateUserWithBodyWithResponse(ctx context.Context, organizationId string, userId string, params *UpdateUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error) {
	rsp, err := c.UpdateUserWithBody(ctx, organizationId, userId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateUserResponse(rsp)
}

func (c *ClientWithResponses) UpdateUserWithResponse(ctx context.Context, organizationId string, userId string, params *UpdateUserParams, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error) {
	rsp, err := c.UpdateUser(ctx, organizationId, userId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateUserResponse(rsp)
}

// ParseGetResourceTypesResponse parses an HTTP response from a GetResourceTypesWithResponse call
func ParseGetResourceTypesResponse(rsp *http.Response) (*GetResourceTypesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetResourceTypesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Resources *[]struct {
				Description *string `json:"description,omitempty"`
				Endpoint    *string `json:"endpoint,omitempty"`
				Id          *string `json:"id,omitempty"`
				Meta        *struct {
					Location     *string `json:"location,omitempty"`
					ResourceType *string `json:"resourceType,omitempty"`
				} `json:"meta,omitempty"`
				Name    *string   `json:"name,omitempty"`
				Schema  *string   `json:"schema,omitempty"`
				Schemas *[]string `json:"schemas,omitempty"`
			} `json:"Resources,omitempty"`
			ItemsPerPage *int      `json:"itemsPerPage,omitempty"`
			Schemas      *[]string `json:"schemas,omitempty"`
			StartIndex   *int      `json:"startIndex,omitempty"`
			TotalResults *int      `json:"totalResults,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseRetrieveUsersSchemaResponse parses an HTTP response from a RetrieveUsersSchemaWithResponse call
func ParseRetrieveUsersSchemaResponse(rsp *http.Response) (*RetrieveUsersSchemaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RetrieveUsersSchemaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Description *string `json:"description,omitempty"`
			Properties  *struct {
				Active *struct {
					Description *string `json:"description,omitempty"`
					Examples    *[]bool `json:"examples,omitempty"`
					Type        *string `json:"type,omitempty"`
				} `json:"active,omitempty"`
				DisplayName *struct {
					Description *string   `json:"description,omitempty"`
					Examples    *[]string `json:"examples,omitempty"`
					Type        *[]string `json:"type,omitempty"`
				} `json:"displayName,omitempty"`
				Emails *struct {
					Description *string `json:"description,omitempty"`
					Examples    *[]struct {
						Primary *bool   `json:"primary,omitempty"`
						Value   *string `json:"value,omitempty"`
					} `json:"examples,omitempty"`
					Items *struct {
						Properties *struct {
							Primary *struct {
								Type *string `json:"type,omitempty"`
							} `json:"primary,omitempty"`
							Type *struct {
								Type *string `json:"type,omitempty"`
							} `json:"type,omitempty"`
							Value *struct {
								Type *string `json:"type,omitempty"`
							} `json:"value,omitempty"`
						} `json:"properties,omitempty"`
						Required *[]string `json:"required,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"items,omitempty"`
					Type *string `json:"type,omitempty"`
				} `json:"emails,omitempty"`
				ExternalId *struct {
					Description *string   `json:"description,omitempty"`
					Examples    *[]string `json:"examples,omitempty"`
					Type        *[]string `json:"type,omitempty"`
				} `json:"externalId,omitempty"`
				Id *struct {
					Description *string   `json:"description,omitempty"`
					Examples    *[]string `json:"examples,omitempty"`
					Type        *string   `json:"type,omitempty"`
				} `json:"id,omitempty"`
				Meta *struct {
					Properties *struct {
						Created *struct {
							Examples *[]string `json:"examples,omitempty"`
							Format   *string   `json:"format,omitempty"`
							Type     *string   `json:"type,omitempty"`
						} `json:"created,omitempty"`
						LastModified *struct {
							Examples *[]string `json:"examples,omitempty"`
							Format   *string   `json:"format,omitempty"`
							Type     *string   `json:"type,omitempty"`
						} `json:"lastModified,omitempty"`
						Location *struct {
							Examples *[]string `json:"examples,omitempty"`
							Format   *string   `json:"format,omitempty"`
							Type     *string   `json:"type,omitempty"`
						} `json:"location,omitempty"`
						ResourceType *struct {
							Examples *[]string `json:"examples,omitempty"`
							Type     *string   `json:"type,omitempty"`
						} `json:"resourceType,omitempty"`
					} `json:"properties,omitempty"`
					Type *string `json:"type,omitempty"`
				} `json:"meta,omitempty"`
				Name *struct {
					Example *struct {
						FamilyName *string `json:"familyName,omitempty"`
						GivenName  *string `json:"givenName,omitempty"`
					} `json:"example,omitempty"`
					Properties *struct {
						FamilyName *struct {
							Type *[]string `json:"type,omitempty"`
						} `json:"familyName,omitempty"`
						GivenName *struct {
							Type *[]string `json:"type,omitempty"`
						} `json:"givenName,omitempty"`
					} `json:"properties,omitempty"`
					Type *string `json:"type,omitempty"`
				} `json:"name,omitempty"`
				Operations *struct {
					Description *string `json:"description,omitempty"`
					Examples    *[]struct {
						Op    *string `json:"op,omitempty"`
						Value *struct {
							Active *bool `json:"active,omitempty"`
						} `json:"value,omitempty"`
					} `json:"examples,omitempty"`
					Items *struct {
						Properties *struct {
							Op *struct {
								Enum *[]string `json:"enum,omitempty"`
								Type *string   `json:"type,omitempty"`
							} `json:"op,omitempty"`
							Path *struct {
								Type *string `json:"type,omitempty"`
							} `json:"path,omitempty"`
							Value *struct {
								OneOf *[]struct {
									Type *string `json:"type,omitempty"`
								} `json:"oneOf,omitempty"`
							} `json:"value,omitempty"`
						} `json:"properties,omitempty"`
						Required *[]string `json:"required,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"items,omitempty"`
					MinItems *int    `json:"minItems,omitempty"`
					Type     *string `json:"type,omitempty"`
				} `json:"operations,omitempty"`
				Roles *struct {
					Items *struct {
						Properties *struct {
							Display *struct {
								Type *string `json:"type,omitempty"`
							} `json:"display,omitempty"`
							Primary *struct {
								Type *string `json:"type,omitempty"`
							} `json:"primary,omitempty"`
							Value *struct {
								Type *string `json:"type,omitempty"`
							} `json:"value,omitempty"`
						} `json:"properties,omitempty"`
						Type *string `json:"type,omitempty"`
					} `json:"items,omitempty"`
					Type *string `json:"type,omitempty"`
				} `json:"roles,omitempty"`
				Schemas *struct {
					Description *string `json:"description,omitempty"`
					Items       *struct {
						Examples *[]string `json:"examples,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"items,omitempty"`
					MinItems *int    `json:"minItems,omitempty"`
					Type     *string `json:"type,omitempty"`
				} `json:"schemas,omitempty"`
				UserName *struct {
					Description *string   `json:"description,omitempty"`
					Examples    *[]string `json:"examples,omitempty"`
					Type        *[]string `json:"type,omitempty"`
				} `json:"userName,omitempty"`
			} `json:"properties,omitempty"`
			Required *[]string `json:"required,omitempty"`
			Title    *string   `json:"title,omitempty"`
			Type     *string   `json:"type,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetServiceProviderConfigResponse parses an HTTP response from a GetServiceProviderConfigWithResponse call
func ParseGetServiceProviderConfigResponse(rsp *http.Response) (*GetServiceProviderConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetServiceProviderConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			AuthenticationSchemes *[]struct {
				Description      *string `json:"description,omitempty"`
				DocumentationUri *string `json:"documentationUri,omitempty"`
				Name             *string `json:"name,omitempty"`
				Primary          *bool   `json:"primary,omitempty"`
				Type             *string `json:"type,omitempty"`
			} `json:"authenticationSchemes,omitempty"`
			Bulk *struct {
				Supported *bool `json:"supported,omitempty"`
			} `json:"bulk,omitempty"`
			ChangePassword *struct {
				Supported *bool `json:"supported,omitempty"`
			} `json:"changePassword,omitempty"`
			DocumentationUri *string `json:"documentationUri,omitempty"`
			Etag             *struct {
				Supported *bool `json:"supported,omitempty"`
			} `json:"etag,omitempty"`
			Filter *struct {
				Supported *bool `json:"supported,omitempty"`
			} `json:"filter,omitempty"`
			Meta *struct {
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name  *string `json:"name,omitempty"`
			Patch *struct {
				Supported *bool `json:"supported,omitempty"`
			} `json:"patch,omitempty"`
			Schemas *[]string `json:"schemas,omitempty"`
			Sort    *struct {
				Supported *bool `json:"supported,omitempty"`
			} `json:"sort,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListUsersResponse parses an HTTP response from a ListUsersWithResponse call
func ParseListUsersResponse(rsp *http.Response) (*ListUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Resources *[]struct {
				Active *bool `json:"active,omitempty"`
				Emails *[]struct {
					Primary *bool   `json:"primary,omitempty"`
					Value   *string `json:"value,omitempty"`
				} `json:"emails,omitempty"`
				ExternalId interface{} `json:"externalId,omitempty"`
				Id         *string     `json:"id,omitempty"`
				Meta       *struct {
					Created      *string `json:"created,omitempty"`
					LastModified *string `json:"lastModified,omitempty"`
					Location     *string `json:"location,omitempty"`
					ResourceType *string `json:"resourceType,omitempty"`
				} `json:"meta,omitempty"`
				Name *struct {
					FamilyName *string `json:"familyName,omitempty"`
					GivenName  *string `json:"givenName,omitempty"`
				} `json:"name,omitempty"`
				Roles *[]struct {
					Display *string `json:"display,omitempty"`
					Primary *bool   `json:"primary,omitempty"`
					Value   *string `json:"value,omitempty"`
				} `json:"roles,omitempty"`
				Schemas  *[]string `json:"schemas,omitempty"`
				UserName *string   `json:"userName,omitempty"`
			} `json:"Resources,omitempty"`
			ItemsPerPage *int      `json:"itemsPerPage,omitempty"`
			Schemas      *[]string `json:"schemas,omitempty"`
			StartIndex   *int      `json:"startIndex,omitempty"`
			TotalResults *int      `json:"totalResults,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseCreateUserResponse parses an HTTP response from a CreateUserWithResponse call
func ParseCreateUserResponse(rsp *http.Response) (*CreateUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Active *bool `json:"active,omitempty"`
			Emails *[]struct {
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"emails,omitempty"`
			ExternalId *string `json:"externalId,omitempty"`
			Id         *string `json:"id,omitempty"`
			Meta       *struct {
				Created      *string `json:"created,omitempty"`
				LastModified *string `json:"lastModified,omitempty"`
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name *struct {
				FamilyName *string `json:"familyName,omitempty"`
				GivenName  *string `json:"givenName,omitempty"`
			} `json:"name,omitempty"`
			Roles *[]struct {
				Display *string `json:"display,omitempty"`
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"roles,omitempty"`
			Schemas  *[]string `json:"schemas,omitempty"`
			UserName *string   `json:"userName,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseDeleteUserResponse parses an HTTP response from a DeleteUserWithResponse call
func ParseDeleteUserResponse(rsp *http.Response) (*DeleteUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 204:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON204 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetUserResponse parses an HTTP response from a GetUserWithResponse call
func ParseGetUserResponse(rsp *http.Response) (*GetUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Active *bool `json:"active,omitempty"`
			Emails *[]struct {
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"emails,omitempty"`
			ExternalId *string `json:"externalId,omitempty"`
			Id         *string `json:"id,omitempty"`
			Meta       *struct {
				Created      *string `json:"created,omitempty"`
				LastModified *string `json:"lastModified,omitempty"`
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name *struct {
				FamilyName *string `json:"familyName,omitempty"`
				GivenName  *string `json:"givenName,omitempty"`
			} `json:"name,omitempty"`
			Roles *[]struct {
				Display *string `json:"display,omitempty"`
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"roles,omitempty"`
			Schemas  *[]string `json:"schemas,omitempty"`
			UserName *string   `json:"userName,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePatchUserResponse parses an HTTP response from a PatchUserWithResponse call
func ParsePatchUserResponse(rsp *http.Response) (*PatchUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Active *bool `json:"active,omitempty"`
			Emails *[]struct {
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"emails,omitempty"`
			ExternalId *string `json:"externalId,omitempty"`
			Id         *string `json:"id,omitempty"`
			Meta       *struct {
				Created      *string `json:"created,omitempty"`
				LastModified *string `json:"lastModified,omitempty"`
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name *struct {
				FamilyName *string `json:"familyName,omitempty"`
				GivenName  *string `json:"givenName,omitempty"`
			} `json:"name,omitempty"`
			Roles *[]struct {
				Display *string `json:"display,omitempty"`
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"roles,omitempty"`
			Schemas  *[]string `json:"schemas,omitempty"`
			UserName *string   `json:"userName,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseUpdateUserResponse parses an HTTP response from a UpdateUserWithResponse call
func ParseUpdateUserResponse(rsp *http.Response) (*UpdateUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Active *bool `json:"active,omitempty"`
			Emails *[]struct {
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"emails,omitempty"`
			ExternalId *string `json:"externalId,omitempty"`
			Id         *string `json:"id,omitempty"`
			Meta       *struct {
				Created      *string `json:"created,omitempty"`
				LastModified *string `json:"lastModified,omitempty"`
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name *struct {
				FamilyName *string `json:"familyName,omitempty"`
				GivenName  *string `json:"givenName,omitempty"`
			} `json:"name,omitempty"`
			Roles *[]struct {
				Display *string `json:"display,omitempty"`
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"roles,omitempty"`
			Schemas  *[]string `json:"schemas,omitempty"`
			UserName *string   `json:"userName,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
