// Package scim is a client for Proof's SCIM 2.0 API, used to provision and
// deprovision users of an organization from an identity provider. Every
// method takes the Proof organization ID. See https://dev.proof.com for the
// API reference.
//
// Create a client with an API key and call it (sandbox shown):
//
//	auth := common.NewAuthenticatedDoer(common.APIKey(os.Getenv("PROOF_API_KEY")))
//	client, err := scim.NewClientWithResponses(common.SandboxURL, scim.WithHTTPClient(auth))
//	if err != nil { ... }
//	resp, err := client.ListUsersWithResponse(ctx, orgID, nil)
//	if err == nil { err = common.CheckResponseBody(resp.HTTPResponse, resp.Body) }
//
// Use the *WithResponse methods of ClientWithResponses and check errors with
// common.CheckResponseBody(resp.HTTPResponse, resp.Body); a nil error from the
// call itself says nothing about the HTTP status.
//
// Quirks of the upstream spec:
//
//   - Responses are untyped: results have no JSON200 field, so decode
//     resp.Body (application/scim+json) into your own struct.
//   - PATCH Operations is an array, but each operation's Value is typed as
//     an object (*map[string]interface{}). To send a string, bool or array
//     value with a path, marshal the body yourself and call
//     PatchUserWithBodyWithResponse with content type application/scim+json.
//
// Code in client.gen.go is generated by oapi-codegen from Proof's OpenAPI
// spec; do not edit it.
package scim
